[pytest]
asyncio_mode = auto
anyio_backend = asyncio
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
markers =
    anyio: mark a test as an anyio coroutine test
    asyncio: mark a test as an asyncio coroutine test

