global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: [alertname, service, team]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-notifications
      group_wait: 10s
      repeat_interval: 30m

    - matchers:
        - severity="warning"
      receiver: warning-notifications
      group_wait: 30s
      repeat_interval: 2h

receivers:
  - name: default
    webhook_configs:
      - url: http://host.docker.internal:5001/alerts/default
        send_resolved: true

  - name: warning-notifications
    webhook_configs:
      - url: http://host.docker.internal:5001/alerts/warning
        send_resolved: true

  - name: critical-notifications
    webhook_configs:
      - url: http://host.docker.internal:5001/alerts/critical
        send_resolved: true

templates: []
